### ISSUE TITLE
Potential secrets committed into Git

### ISSUE THREAD

**Issue by ssddanbrown** [DocsPen/Platform#96]
Just a friendly warning, It looks like secrets have been committed into git and are thus public:

https://raw.githubusercontent.com/DocsPen/Platform/master/.env.prod

Would advise removal if legitimate and the changing of all secrets/passwords in this file.

**Comment by yoginth** [comment]
thanks for notifying @ssddanbrown!

**Comment by yoginth** [comment]
Fixed in https://github.com/DocsPen/Platform/commit/c4b33fa86403a2dbc6762c7d92e06556ae79cb2e
